### ISSUE TITLE
Provide gen of Java classes

### ISSUE THREAD

**Issue by kurb70** [ikeough/IFC-gen#12]
Interesting project. Would you please provide a description/example how to gen Java code?

**Comment by ikeough** [comment]
I’ve updated the README to provide some details about how to implement a language generator. A java language generator would look very similar to the C# one. It should be as simple as creating a JavaLanguageGenerator and extending Program.cs to understand a “java” flag.

**Comment by ikeough** [comment]
Alternatively, I’ve added protocol buffer support. Protocol buffers supports compilation to Java. So, you could use the auto-generated java code created by the protocol buffers compiler. This generates highly unreadable java code however which includes a whole bunch of pbuf support code. This might not be to your liking.

**Comment by kurb70** [comment]
Thank you for explaining. Unfortunately, I don't understand how the whole project works well enough to be able to contribute something useful.

**Comment by ikeough** [comment]
I’m going to close this now, but am willing to lend support in the future if anyone wants to work on java generation.

**Comment by simiii** [comment]
I am highly interested in providing the java language generator.
When I understand the project correctly - what I will get is a bunch of java source files, which enable me to parse IFCStep-Files into a (java) model? 

Would it make sense to redistribute the generated classes over maven central as a library enabling java people to make use of the library and further easily use the library to process IFC content in their programs?
