### ISSUE TITLE
building on macOS failed

### ISSUE THREAD

**Issue by kurb70** [ikeough/IFC-gen#15]
ReadMe mentioned that building for macOS should be possibe with `make`.

If I execute `make` I'm getting:

```
kubasMBPr:IFC-gen kuba$ make
dotnet build ./src/IFC-gen.csproj
make: dotnet: No such file or directory
make: *** [ifc-gen] Error 1
```

Are there any other prerequisites that are not yet described?

**Comment by ikeough** [comment]
@kurb70 You'll need to install dotnet core, as suggested in the Prerequisites section of the README. If installing the same does not solve the issue, please let me know.

**Comment by kurb70** [comment]
Thank you. After installing dotnet core it comiled as expected.
