### ISSUE TITLE
Class Prefix

### ISSUE THREAD

**Issue by jmirtsch** [ikeough/IFC-gen#9]
Hi Ian,

Here's a suggestion if you don't mind (which was suggested to me some time ago).

If you are generating additional classes to assist the IFC schema classes, it's better to suffix the identifier "ifc" rather than prefix.  Ie BaseIfc rather than IfcBase.  

If someone new to Ifc is reviewing your code, they can differentiate between them and not search through building smart documentation for a class that doesn't exist.  

Cheers,

Jon

**Comment by ikeough** [comment]
Hey @jmirtsch that's a very valid point. I'll do it.

**Comment by ikeough** [comment]
This is updated in ea0f16176c6b952c08d20d6c2e3b149b433d3ea7.
